# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-04 15:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Final',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(db_column='DateTime')),
                ('module', models.CharField(blank=True, db_column='Module', max_length=30, null=True)),
                ('avgnumwificonn', models.FloatField(blank=True, db_column='AvgNumWifiConn', null=True)),
                ('groundtruth', models.FloatField(blank=True, db_column='GroundTruth', null=True)),
            ],
            options={
                'db_table': 'Final',
            },
        ),
        migrations.CreateModel(
            name='Modules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moduletitle', models.CharField(blank=True, db_column='ModuleTitle', max_length=30, null=True)),
                ('numberregistered', models.IntegerField(blank=True, db_column='NumberRegistered', null=True)),
            ],
            options={
                'db_table': 'Modules',
            },
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('room', models.CharField(db_column='Room', max_length=10, primary_key=True, serialize=False)),
                ('capacity', models.IntegerField(db_column='Capacity')),
            ],
            options={
                'db_table': 'Rooms',
            },
        ),
        migrations.AddField(
            model_name='final',
            name='room',
            field=models.ForeignKey(db_column='Room', on_delete=django.db.models.deletion.DO_NOTHING, to='occupants.Rooms'),
        ),
        migrations.AlterUniqueTogether(
            name='final',
            unique_together=set([('datetime', 'room')]),
        ),
    ]
