# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-07 15:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Groundtruth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(db_column='DateTime')),
                ('binaryestimate', models.IntegerField(blank=True, db_column='BinaryEstimate', null=True)),
                ('percentageestimate', models.FloatField(blank=True, db_column='PercentageEstimate', null=True)),
            ],
            options={
                'db_table': 'GroundTruth',
            },
        ),
        migrations.CreateModel(
            name='Modules',
            fields=[
                ('modulename', models.CharField(db_column='ModuleName', max_length=30, primary_key=True, serialize=False)),
                ('numreg', models.IntegerField(blank=True, db_column='NumReg', null=True)),
            ],
            options={
                'db_table': 'Modules',
            },
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('room', models.CharField(db_column='Room', max_length=10, primary_key=True, serialize=False)),
                ('building', models.CharField(blank=True, db_column='Building', max_length=30, null=True)),
                ('campus', models.CharField(blank=True, db_column='Campus', max_length=30, null=True)),
                ('capacity', models.IntegerField(blank=True, db_column='Capacity', null=True)),
            ],
            options={
                'db_table': 'Rooms',
            },
        ),
        migrations.CreateModel(
            name='Timemodule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(db_column='DateTime')),
                ('module', models.ForeignKey(db_column='Module', on_delete=django.db.models.deletion.DO_NOTHING, to='occupants.Modules')),
                ('room', models.ForeignKey(db_column='Room', on_delete=django.db.models.deletion.DO_NOTHING, to='occupants.Rooms')),
            ],
            options={
                'db_table': 'TimeModule',
            },
        ),
        migrations.CreateModel(
            name='Wifilogdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(db_column='DateTime')),
                ('associated', models.IntegerField(blank=True, db_column='Associated', null=True)),
                ('authenticated', models.IntegerField(blank=True, db_column='Authenticated', null=True)),
                ('room', models.ForeignKey(db_column='Room', on_delete=django.db.models.deletion.DO_NOTHING, to='occupants.Rooms')),
            ],
            options={
                'db_table': 'WiFiLogData',
            },
        ),
        migrations.AddField(
            model_name='groundtruth',
            name='room',
            field=models.ForeignKey(db_column='Room', on_delete=django.db.models.deletion.DO_NOTHING, to='occupants.Rooms'),
        ),
        migrations.AlterUniqueTogether(
            name='wifilogdata',
            unique_together=set([('datetime', 'room')]),
        ),
        migrations.AlterUniqueTogether(
            name='timemodule',
            unique_together=set([('datetime', 'room')]),
        ),
        migrations.AlterUniqueTogether(
            name='groundtruth',
            unique_together=set([('datetime', 'room')]),
        ),
    ]
