# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-07 16:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('occupants', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groundtruth',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='modules',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='rooms',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='timemodule',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='wifilogdata',
            options={'managed': False},
        ),
    ]
