# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-28 15:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('occupants', '0002_auto_20160728_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groundtruth',
            name='groundtruthid',
            field=models.AutoField(db_column='GroundTruthId', primary_key=True, serialize=False),
        ),
    ]
