# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-07 22:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('occupants', '0002_auto_20160707_1630'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rooms',
            options={},
        ),
    ]
