# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-07 23:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('occupants', '0003_auto_20160707_2223'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rooms',
            options={'managed': False},
        ),
    ]
