# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-08 12:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('occupants', '0004_auto_20160707_2304'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rooms',
            options={},
        ),
    ]
