# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-08 13:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('occupants', '0005_auto_20160708_1234'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groundtruth',
            options={},
        ),
        migrations.AlterModelOptions(
            name='modules',
            options={},
        ),
        migrations.AlterModelOptions(
            name='timemodule',
            options={},
        ),
        migrations.AlterModelOptions(
            name='wifilogdata',
            options={},
        ),
    ]
